server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/turf_booking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MySQL8.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.cache.period=0

turf.jwt.secret=ChangeThisJwtSecretToAtLeastThirtyTwoCharactersForProductionUse
turf.jwt.expiration-ms=86400000
f